### ISSUE TITLE
Validation error CII-SR-175 & CII-DT-027

### ISSUE THREAD

**Issue by 0xD0M1M0** [alyf-de/eu_einvoice#13]
Output of "Validation Check" of an eu_einvoice generated e-invoice:
```
------------------------
Europäische Rechnung
------------------------
[CII-SR-175] - DeliveryNoteReferencedDocument should not be present
[CII-DT-027] - FormattedIssueDateTime should not be present
```

Source of errors:
https://github.com/alyf-de/eu_einvoice/blob/bac24747b448b1cbf8f9f32ec1ee6252926d8145/eu_einvoice/european_e_invoice/custom/sales_invoice.py#L301-L305

https://github.com/alyf-de/eu_einvoice/blob/bac24747b448b1cbf8f9f32ec1ee6252926d8145/eu_einvoice/european_e_invoice/custom/sales_invoice.py#L118-L119

**Comment by barredterra** [comment]
It looks like these elements are supported in the "EXTENDED" profile, but not in the "EN16931" profile. A solution could be to make the profile configurable for export: offer a dropdown with options "EN16931" / "EXTENDED" / "XRECHNUNG", take care to export only supported elements, run the suitable validations only.

A good place to find the supported elements are the ZUGFeRD spec for  "EN16931" / "EXTENDED" and the XRechnung spec for "XRECHNUNG".
