### ISSUE TITLE
Cannot install eu_einvoice: Could not find app "frappe/erpnext"

### ISSUE THREAD

**Issue by Bi0max** [alyf-de/eu_einvoice#15]
I run `bench install-app eu_einvoice`, but it gives me an error:
```
Could not find app "frappe/erpnext"
No module named 'frappe/erpnext'
```
Even though erpnext is installed.

```
$ bench list-apps
frappe  13.58.21 version-13
erpnext 13.55.2  version-13
```

**Comment by barredterra** [comment]
Version 13 is not supported. At the moment, you'll need at least version 15.

**Comment by Bi0max** [comment]
@barredterra , hi, could you say, is it planned to support more versions in the next weeks?

**Comment by barredterra** [comment]
Yes, support for v14 will be added this month.
v13 has reached it's end of life and will not be considered.
