### ISSUE TITLE
Ability to provide SEPA information

### ISSUE THREAD

**Issue by carstenblt** [alyf-de/eu_einvoice#19]
For direct debit we would need to set `CreditorReferenceID`, `PayerPartyDebtorFinancialAccount`, `DirectDebitMandateID`. ERPNext does not provide a data model for this, but you could maybe add an option to use a custom field in the Invoice doc?

For a SEPA transfer it would be `PayeePartyCreditorFinancialAccount.IBANID`, `PayeePartyCreditorFinancialAccount.BICID`, `PayeePartyCreditorFinancialAccount.AccountName`. I think ERPNext does not link a "Bank Account" doc to a Payment Term, so this would have to be configured differently too.

**Comment by barredterra** [comment]
I'm not sure about the design yet. Ideas:

- Bank account details: already stored in **Bank Account** and **Bank**. Add a link to the table in **Mode of Payment**, for referencing a specific **Bank Account**? Or just use the company's _Default Bank Account_?
- SEPA Direct Debit Mandate: a new DocType, linked to a **Customer** and selectable in a **Sales Invoice**?

**Comment by 0xD0M1M0** [comment]
Concerning SEPA Direct Debit Mandate, I do not have much experience with it, but a new DocType would make sense to cover the points mentioned as required information here: [https://schufa-und-finanzen.net/sepa-lastschriftverfahren/](https://schufa-und-finanzen.net/sepa-lastschriftverfahren/). Sales Invoice would be the last point to link it, and here I am not sure, if the Direct Debit Mandate is linked to a specific order or abo or is generic for the customer. In any case, it might me useful to start the link in the order itself.

For the Bank Account details, I see a long chain of links: The **bank account** is linked with an **account**. The **account** is linked with a **Mode of Payment**. The **Mode of Payment** is linked in the **Payment Term**, which is linked in the **Sales Invoice**. 

As at least in Germany each **account** is assigned to one **bank account**, the data is available.

**Comment by barredterra** [comment]
I'll skip the _SEPA Direct Debit Mandate_ for now, since this feature is not available in ERPNext yet. Feel free to open a feature request on https://github.com/frappe/erpnext with detailed requirements.
