### ISSUE TITLE
Missing field for UOM

### ISSUE THREAD

**Issue by itsdaveit** [alyf-de/eu_einvoice#2]
Since we have

row.uom = frappe.db.get_value("UOM", {"common_code": row.unit_code}, "name")

im missing the field common_code in Doctype UOM. Maybe forgot export customizations for UOM?

```
def guess_uom(self):
		for row in self.items:
			if row.uom:
				continue

			if row.unit_code:
				row.uom = frappe.db.get_value("UOM", {"common_code": row.unit_code}, "name")
			elif row.item:
				stock_uom, purchase_uom = frappe.db.get_value("Item", row.item, ["stock_uom", "purchase_uom"])
				row.uom = purchase_uom or stock_uom
```

**Comment by barredterra** [comment]
@itsdaveit FYI, I'm currently developing against the `develop` branch of frappe and erpnext. Backports will follow at a later point.

Relevant PR: https://github.com/frappe/erpnext/pull/43425

**Comment by itsdaveit** [comment]
Oh, thanks, i did not know about https://github.com/frappe/erpnext/pull/43425.
