### ISSUE TITLE
E-Invoice Validation fails [BR-CO-15]

### ISSUE THREAD

**Issue by 0xD0M1M0** [alyf-de/eu_einvoice#6]
I set up a sample invoice (1 item / 100€ plus 19% tax):

The E-invoice generated states at the end:
```
<ram:SpecifiedTradeSettlementHeaderMonetarySummation>
<ram:LineTotalAmount>100.0</ram:LineTotalAmount>
<ram:ChargeTotalAmount>0.00</ram:ChargeTotalAmount>
<ram:AllowanceTotalAmount>0.0</ram:AllowanceTotalAmount>
<ram:TaxBasisTotalAmount>100.0</ram:TaxBasisTotalAmount>
<ram:TaxTotalAmount>19.0</ram:TaxTotalAmount>
<ram:GrandTotalAmount>119.0</ram:GrandTotalAmount>
<ram:TotalPrepaidAmount>0.0</ram:TotalPrepaidAmount>
<ram:DuePayableAmount>119.0</ram:DuePayableAmount>
</ram:SpecifiedTradeSettlementHeaderMonetarySummation>
```

**Failure:**
The validation with "https://www.itb.ec.europa.eu/invoice/upload" fails with:
`[BR-CO-15]-Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).`

**Solution:**
- add currencyID in the following line: <ram:TaxTotalAmount currencyID="EUR">19.0</ram:TaxTotalAmount>

**Comment by barredterra** [comment]
Thanks for investigating. Interesting solution, though. Do you know why tax is the only element that requires specifying the currency?

**Comment by 0xD0M1M0** [comment]
No idea. When adding it to the other lines, the following error occurs:
`[CII-DT-031] - currencyID should not be present`

I cross validated with [https://erechnungsvalidator.service-bw.de/](https://erechnungsvalidator.service-bw.de/) with the same result.

Funnily, in an ZUGPFeRD documentation from 2014 all lines in that section had the currencyID.

**Comment by 0xD0M1M0** [comment]
Found it (but somehow for BT-111 not BT-110):
![grafik](https://github.com/user-attachments/assets/1e771a89-44f7-406d-8387-0e158159d034)

Source: https://xeinkauf.de/app/uploads/2024/07/302-XRechnung-2024-06-20.pdf

**Comment by 0xD0M1M0** [comment]
https://github.com/alyf-de/eu_einvoice/blob/3ffbcce749ceb01980ded5181c13004179797211/eu_einvoice/european_e_invoice/custom/sales_invoice.py#L320

likely needs to be changed to:
```
tax_total_other_currency: CurrencyContainer = MultiCurrencyField(
        NS_RAM, "TaxTotalAmount", profile=EXTENDED, _d="Steuergesamtbetrag"
    )
```

see:
https://github.com/pretix/python-drafthorse/blob/5c45ef040a340ddd5e244599c42785195ee26165/drafthorse/models/accounting.py#L149-L154
