### ISSUE TITLE
Unknown column 'common_code'

### ISSUE THREAD

**Issue by 0xD0M1M0** [alyf-de/eu_einvoice#7]
### App Versions
```
{
	"erpnext": "15.43.3",
	"erpnext_germany": "15.9.1",
	"eu_einvoice": "0.0.1",
	"frappe": "15.48.0",
}
```

### Response Data
```
File "apps/eu_einvoice/eu_einvoice/european_e_invoice/doctype/e_invoice_import/e_invoice_import.py", line 85, in before_save
    self.guess_uom()
  File "apps/eu_einvoice/eu_einvoice/european_e_invoice/doctype/e_invoice_import/e_invoice_import.py", line 231, in guess_uom
    row.uom = frappe.db.get_value("UOM", {"common_code": row.unit_code}, "name")

{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'common_code' in 'where clause'\")",
	"exc_type": "OperationalError",
	"_exc_source": "eu_einvoice (app)"
}
```

### Failure
ERPNext version 15 and below do not know the column "common_code". This is only a feature of the "develop" branch.

**Comment by 0xD0M1M0** [comment]
The solution looks good and is definitely better than assigning one time the UoM in the code list and then vice versa.

What happens if the UoM is assigned multiple times due to an error in the code list?

**Comment by barredterra** [comment]
> What happens if the UoM is assigned multiple times due to an error in the code list?

The same UOM cannot be assigned to multiple codes of the same list.

If multiple UOMs are assigned to the same code, we take the first one in the table.
