### ISSUE TITLE
E-Invoice Validation fails

### ISSUE THREAD

**Issue by 0xD0M1M0** [alyf-de/eu_einvoice#8]
Validation with [https://erechnungsvalidator.service-bw.de/](https://erechnungsvalidator.service-bw.de/) throws some informations and warnings. 

At least BR-DE-5 seems fixable, probably with a field in the company DocType. I personally would prefer, if all three seller contact fields would be new fields in the company DocType (only fall back to the defaults), so that the accounting department can be reached seperatly independent from business letters or so.

BR-DE-26 seems not be included in the drafthorse library (XRechnung 2.2) - Validated against XRechnung 3.0.2 which superseeded XRechnung 2.3 on 01. February 2024.

Reference: https://xeinkauf.de/app/uploads/2024/07/302-XRechnung-2024-06-20.pdf

val-sch.2.1 	PEPPOL-EN16931-R001 	information 	Business process MUST be provided.
Pfad: /rsm:CrossIndustryInvoice/rsm:ExchangedDocumentContext[1] ✅ 

val-sch.2.2 	PEPPOL-EN16931-R020 	information 	Seller electronic address MUST be provided
Pfad: /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction[1]/ram:ApplicableHeaderTradeAgreement[1]/ram:SellerTradeParty[1] ✅

val-sch.2.3 	PEPPOL-EN16931-R010 	information 	Buyer electronic address MUST be provided
Pfad: /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction[1]/ram:ApplicableHeaderTradeAgreement[1]/ram:BuyerTradeParty[1] ✅

val-sch.2.4 	BR-DE-26 	warning 	[BR-DE-26] Wenn im Element Invoice type code (BT-3) der Code 384 (Corrected invoice) übergeben wird, soll PRECEDING INVOICE REFERENCE BG-3 mind. einmal vorhanden sein.
Pfad: /rsm:CrossIndustryInvoice  ✅ 

val-sch.2.5 	BR-DE-21 	warning 	[BR-DE-21] Das Element "Specification identifier" (BT-24) soll syntaktisch der Kennung des Standards XRechnung entsprechen.
Pfad: /rsm:CrossIndustryInvoice/rsm:ExchangedDocumentContext[1] ✅

val-sch.2.6 	BR-DE-5 	warning 	[BR-DE-5] Das Element "Seller contact point" (BT-41) muss übermittelt werden.
Pfad: /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction[1]/ram:ApplicableHeaderTradeAgreement[1]/ram:SellerTradeParty[1]/ram:DefinedTradeContact[1]  ✅ 

val-sch.2.7 	BR-DE-19 	warning 	[BR-DE-19] "Payment account identifier" (BT-84) soll eine korrekte IBAN enthalten, wenn in "Payment means type code" (BT-81) mit dem Code 58 SEPA als Zahlungsmittel gefordert wird.
Pfad: /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction[1]/ram:ApplicableHeaderTradeSettlement[1]/ram:SpecifiedTradeSettlementPaymentMeans[1]

val-sch.2.8 	BR-DE-23-a 	error 	[BR-DE-23-a] Wenn BT-81 "Payment means type code" einen Schlüssel für Überweisungen enthält (30, 58), muss BG-17 "CREDIT TRANSFER" übermittelt werden.
Pfad: /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction[1]/ram:ApplicableHeaderTradeSettlement[1]/ram:SpecifiedTradeSettlementPaymentMeans[1]

**Comment by barredterra** [comment]
The PEPPOL errors are not relevant, since we don't support this at the moment.

BR-DE-5 is a configuration issue, fixable by setting _Email_ and _Phone No_ in the **Company**.

The rest seems valid.

**Comment by 0xD0M1M0** [comment]
Seller contact point (BT-41) is a text field for a person name, department or office. Email and phone are not enough.

**Comment by barredterra** [comment]
Adding _Company Contact Person_ to all sales transactions: https://github.com/frappe/erpnext/pull/44362

**Comment by barredterra** [comment]
> Validation with [erechnungsvalidator.service-bw.de](https://erechnungsvalidator.service-bw.de/) throws some informations and warnings.

**E Invoice Import** can now do this - no more need for third party validators 🎉

**Comment by barredterra** [comment]
Closing this for now. Support for specifying a bank account is still on the to do list.
